---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}

library(tidyr)
library(readr)
library(ggplot2)
library(dplyr)
library(stringr)
library(plotly)

```

Reading in MappingMuseumData:

```{r read-in-data}

museum_df <- read_csv("MappingMuseumsData2021_09_30.csv")

```
```{r tidy-up-data}
tidy_museum_df <- museum_df %>%
  pivot_longer(cols = c(starts_with("Area_Deprivation_Index")), names_to = "Area_Deprivation_Type", values_to = "Area_Deprivation_Score") %>%
  select(-ends_with("_provenance"),-starts_with("DOMUS"),-ends_with("_code")) %>%
  mutate(status = "open") %>%
  mutate(status = ifelse(Year_closed != "9999:9999","closed",status))
```

```{r viz-sum-open-vs-deprivation}
tidy_museum_sum <- tidy_museum_df %>%
  filter(Area_Deprivation_Type != "Area_Deprivation_index") %>%
  separate(col = "Area_Deprivation_Type", into = c(NA,NA,NA,"Area_Deprivation_Type"),sep = "_") %>%
  group_by(Area_Deprivation_Type,Area_Deprivation_Score,status) %>%
  summarize(n = n())
  
ggp <- ggplot(tidy_museum_sum,aes(x = Area_Deprivation_Score,y = n, fill = status)) +
  geom_col(position = "dodge") +
  facet_wrap("Area_Deprivation_Type",) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  theme_classic()

ggplotly(ggp,tooltip = c("x","y","status"))
```
